# Generated by Django 5.0.6 on 2026-02-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_seed_movement_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedtransaction',
            name='classification',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('cdt', 'CDT'), ('bolsillo', 'Bolsillo')], default='gasto', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='classification',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('cdt', 'CDT'), ('bolsillo', 'Bolsillo')], default='gasto', max_length=16),
        ),
        migrations.AlterField(
            model_name='stagedtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('skipped', 'Omitida'), ('deleted', 'Eliminada')], default='pending', max_length=16),
        ),
    ]
