# Generated by Django 5.0.6 on 2026-02-26 17:00

from django.db import migrations


def get_classification(movement_name: str) -> str:
    name = (movement_name or "").lower()
    if name in ["abono", "transferencia"]:
        return "ingreso"
    elif name == "cdt":
        return "cdt"
    elif name == "bolsillo":
        return "bolsillo"
    else:
        return "gasto"


def populate_classification(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    for tx in Transaction.objects.all():
        if tx.movement_type:
            tx.classification = get_classification(tx.movement_type.name)
            tx.save(update_fields=['classification'])

    StagedTransaction = apps.get_model('transactions', 'StagedTransaction')
    for stx in StagedTransaction.objects.all():
        if stx.movement_type:
            stx.classification = get_classification(stx.movement_type.name)
            stx.save(update_fields=['classification'])


def reverse_populate_classification(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_stagedtransaction_classification_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_classification, reverse_populate_classification),
    ]
